### ISSUE TITLE
 Cannot invoke "java.lang.ClassLoader.loadClass(String)" because "class_loader" is null

### ISSUE THREAD

**Issue by idhowardgj94** [polyfy/polylith#421]
**Describe the bug**
When I trying to run test by following command, nullpointerexception happened

```bash
poly test :all :dev                                                                     1 ↵  08:42:59  
Projects to run tests from: development

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Couldn't create classloader for paths: ["bases/api-server/resources" "bases/api-server/src" "components/auth/resources" "components/auth/src" "components/channels/resources" "components/channels/src" "components/database/resources" "components/database/src" "components/messages/resources" "components/messages/src" "components/socket/resources" "components/socket/src" "components/subscriptions/resources" "components/subscriptions/src" "components/teams/resources" "components/teams/src" "components/tools/resources" "components/tools/src" "components/users/resources" "components/users/src" "development/resources" "development/src" "bases/api-server/test" "components/auth/test" "components/channels/test" "components/database/test" "components/messages/test" "components/socket/test" "components/subscriptions/test" "components/teams/test" "components/tools/test" "components/users/test" "/Users/howard/.m2/repository/funcool/cuerdas/2020.03.26-3/cuerdas-2020.03.26-3.jar" "/Users/howard/.m2/repository/org/bouncycastle/bcpkix-jdk18on/1.75/bcpkix-jdk18on-1.75.jar" "/Users/howard/.m2/repository/io/methvin/directory-watcher/0.17.1/directory-watcher-0.17.1.jar" "/Users/howard/.m2/repository/cider/piggieback/0.5.3/piggieback-0.5.3.jar" "/Users/howard/.m2/repository/org/clojure/test.check/1.1.1/test.check-1.1.1.jar" "/Users/howard/.m2/repository/ring/ring-codec/1.2.0/ring-codec-1.2.0.jar" "/Users/howard/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar" "/Users/howard/.m2/repository/org/clojure/data.xml/0.2.0-alpha6/data.xml-0.2.0-alpha6.jar" "/Users/howard/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar" "/Users/howard/.m2/repository/metosin/reitit-spec/0.5.18/reitit-spec-0.5.18.jar" "/Users/howard/.m2/repository/buddy/buddy-auth/3.0.323/buddy-auth-3.0.323.jar" "/Users/howard/.m2/repository/org/eclipse/jetty/jetty-io/9.4.44.v20210927/jetty-io-9.4.44.v20210927.jar" "/Users/howard/.m2/repository/args4j/args4j/2.33/args4j-2.33.jar" "/Users/howard/.m2/repository/org/apache/ant/ant-launcher/1.10.11/ant-launcher-1.10.11.jar" "/Users/howard/.m2/repository/http-kit/http-kit/2.7.0/http-kit-2.7.0.jar" "/Users/howard/.m2/repository/org/ow2/asm/asm/9.2/asm-9.2.jar" "/Users/howard/.m2/repository/metosin/reitit/0.5.18/reitit-0.5.18.jar" "/Users/howard/.m2/repository/org/apache/maven/resolver/maven-resolver-spi/1.6.3/maven-resolver-spi-1.6.3.jar" "/Users/howard/.m2/repository/net/cgrand/macrovich/0.2.1/macrovich-0.2.1.jar" "/Users/howard/.m2/repository/cljs-ajax/cljs-ajax/0.8.4/cljs-ajax-0.8.4.jar" "/Users/howard/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar" "/Users/howard/.m2/repository/com/teknql/shadow-cljs-tailwind-jit/1.0.0/shadow-cljs-tailwind-jit-1.0.0.jar" "/Users/howard/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.6.3/maven-resolver-util-1.6.3.jar" "/Users/howard/.m2/repository/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar" "/Users/howard/.m2/repository/hiccup/hiccup/1.0.5/hiccup-1.0.5.jar" "/Users/howard/.m2/repository/org/clojure/tools.logging/1.2.4/tools.logging-1.2.4.jar" "/Users/howard/.m2/repository/buddy/buddy-core/1.11.423/buddy-core-1.11.423.jar" "/Users/howard/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar" "/Users/howard/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar" "/Users/howard/.m2/repository/com/cognitect/transit-cljs/0.8.280/transit-cljs-0.8.280.jar" "/Users/howard/.m2/repository/ring/ring-core/1.8.2/ring-core-1.8.2.jar" "/Users/howard/.m2/repository/com/cognitect/aws/s3/814.2.1053.0/s3-814.2.1053.0.jar" "/Users/howard/.m2/repository/org/clojure/core.memoize/1.0.253/core.memoize-1.0.253.jar" "/Users/howard/.m2/repository/borkdude/sci.impl.reflector/0.0.1/sci.impl.reflector-0.0.1.jar" "/Users/howard/.m2/repository/metosin/reitit-schema/0.5.18/reitit-schema-0.5.18.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-settings-builder/3.8.4/maven-settings-builder-3.8.4.jar" "/Users/howard/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar" "/Users/howard/.m2/repository/org/bouncycastle/bcutil-jdk18on/1.75/bcutil-jdk18on-1.75.jar" "/Users/howard/.m2/repository/tigris/tigris/0.1.2/tigris-0.1.2.jar" "/Users/howard/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar" "/Users/howard/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.5/org.eclipse.sisu.plexus-0.3.5.jar" "/Users/howard/.m2/repository/org/apache/httpcomponents/httpmime/4.5.13/httpmime-4.5.13.jar" "/Users/howard/.m2/repository/org/babashka/sci/0.7.39/sci-0.7.39.jar" "/Users/howard/.m2/repository/com/taoensso/timbre/6.2.2/timbre-6.2.2.jar" "/Users/howard/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar" "/Users/howard/.m2/repository/thheller/shadow-undertow/0.3.1/shadow-undertow-0.3.1.jar" "/Users/howard/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.30/jcl-over-slf4j-1.7.30.jar" "/Users/howard/.m2/repository/dev/weavejester/ragtime.jdbc/0.9.3/ragtime.jdbc-0.9.3.jar" "/Users/howard/.m2/repository/commons-fileupload/commons-fileupload/1.4/commons-fileupload-1.4.jar" "/Users/howard/.m2/repository/metosin/reitit-ring/0.5.18/reitit-ring-0.5.18.jar" "/Users/howard/.m2/repository/clj-stacktrace/clj-stacktrace/0.2.8/clj-stacktrace-0.2.8.jar" "/Users/howard/.m2/repository/org/jboss/xnio/xnio-nio/3.8.0.Final/xnio-nio-3.8.0.Final.jar" "/Users/howard/.m2/repository/org/clojure/java.jdbc/0.7.12/java.jdbc-0.7.12.jar" "/Users/howard/.m2/repository/org/codehaus/plexus/plexus-cipher/2.0/plexus-cipher-2.0.jar" "/Users/howard/.m2/repository/org/clojure/google-closure-library/0.0-20211011-0726fdeb/google-closure-library-0.0-20211011-0726fdeb.jar" "/Users/howard/.m2/repository/mvxcvi/arrangement/2.0.0/arrangement-2.0.0.jar" "/Users/howard/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar" "/Users/howard/.m2/repository/org/apache/maven/resolver/maven-resolver-api/1.6.3/maven-resolver-api-1.6.3.jar" "/Users/howard/.m2/repository/ring/ring-defaults/0.3.4/ring-defaults-0.3.4.jar" "/Users/howard/.m2/repository/cheshire/cheshire/5.11.0/cheshire-5.11.0.jar" "/Users/howard/.m2/repository/org/wildfly/common/wildfly-common/1.5.2.Final/wildfly-common-1.5.2.Final.jar" "/Users/howard/.m2/repository/resauce/resauce/0.2.0/resauce-0.2.0.jar" "/Users/howard/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.13.3/jackson-dataformat-smile-2.13.3.jar" "/Users/howard/.m2/repository/org/clojure/tools.namespace/0.2.11/tools.namespace-0.2.11.jar" "/Users/howard/.m2/repository/slingshot/slingshot/0.12.2/slingshot-0.12.2.jar" "/Users/howard/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar" "/Users/howard/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.jar" "/Users/howard/.m2/repository/com/google/javascript/closure-compiler-unshaded/v20230103/closure-compiler-unshaded-v20230103.jar" "/Users/howard/.m2/repository/com/github/seancorfield/next.jdbc/1.3.883/next.jdbc-1.3.883.jar" "/Users/howard/.m2/repository/metosin/muuntaja/0.6.8/muuntaja-0.6.8.jar" "/Users/howard/.m2/repository/expound/expound/0.9.0/expound-0.9.0.jar" "/Users/howard/.m2/repository/integrant/integrant/0.8.1/integrant-0.8.1.jar" "/Users/howard/.m2/repository/riddley/riddley/0.1.12/riddley-0.1.12.jar" "/Users/howard/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar" "/Users/howard/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar" "/Users/howard/.m2/repository/org/postgresql/postgresql/42.2.10/postgresql-42.2.10.jar" "/Users/howard/.m2/repository/metosin/reitit-interceptors/0.5.18/reitit-interceptors-0.5.18.jar" "/Users/howard/.m2/repository/zprint/zprint/1.2.7/zprint-1.2.7.jar" "/Users/howard/.m2/repository/com/lambdaworks/scrypt/1.4.0/scrypt-1.4.0.jar" "/Users/howard/.m2/repository/fipp/fipp/0.6.26/fipp-0.6.26.jar" "/Users/howard/.m2/repository/com/cognitect/aws/endpoints/1.1.12.150/endpoints-1.1.12.150.jar" "/Users/howard/.m2/repository/tech/droit/clj-diff/1.0.1/clj-diff-1.0.1.jar" "/Users/howard/.m2/repository/metosin/reitit-core/0.5.18/reitit-core-0.5.18.jar" "/Users/howard/.m2/repository/org/codehaus/plexus/plexus-sec-dispatcher/2.0/plexus-sec-dispatcher-2.0.jar" "/Users/howard/.m2/repository/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-model/3.8.4/maven-model-3.8.4.jar" "/Users/howard/.m2/repository/org/apache/ant/ant/1.10.11/ant-1.10.11.jar" "/Users/howard/.m2/repository/com/cognitect/http-client/1.0.110/http-client-1.0.110.jar" "/Users/howard/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-file/1.6.3/maven-resolver-transport-file-1.6.3.jar" "/Users/howard/.m2/repository/com/yahoo/platform/yui/yuicompressor/2.4.8/yuicompressor-2.4.8.jar" "/Users/howard/.m2/repository/org/clojure/tools.cli/1.0.206/tools.cli-1.0.206.jar" "/Users/howard/.m2/repository/org/clojure/core.specs.alpha/0.2.62/core.specs.alpha-0.2.62.jar" "/Users/howard/.m2/repository/buddy/buddy-sign/3.4.333/buddy-sign-3.4.333.jar" "/Users/howard/.m2/repository/camel-snake-kebab/camel-snake-kebab/0.4.3/camel-snake-kebab-0.4.3.jar" "/Users/howard/.m2/repository/crypto-random/crypto-random/1.2.0/crypto-random-1.2.0.jar" "/Users/howard/.m2/repository/clojurewerkz/scrypt/1.2.0/scrypt-1.2.0.jar" "/Users/howard/.m2/repository/metosin/schema-tools/0.12.3/schema-tools-0.12.3.jar" "/Users/howard/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar" "/Users/howard/.m2/repository/dev/weavejester/ragtime.next-jdbc/0.9.3/ragtime.next-jdbc-0.9.3.jar" "/Users/howard/.m2/repository/org/clojure/tools.macro/0.1.5/tools.macro-0.1.5.jar" "/Users/howard/.m2/repository/ring/ring-json/0.5.1/ring-json-0.5.1.jar" "/Users/howard/.m2/repository/metosin/sieppari/0.0.0-alpha13/sieppari-0.0.0-alpha13.jar" "/Users/howard/.m2/repository/org/msgpack/msgpack/0.6.12/msgpack-0.6.12.jar" "/Users/howard/.m2/repository/org/eclipse/jetty/jetty-http/9.4.44.v20210927/jetty-http-9.4.44.v20210927.jar" "/Users/howard/.m2/repository/clout/clout/2.2.1/clout-2.2.1.jar" "/Users/howard/.m2/repository/com/cognitect/aws/api/0.8.539/api-0.8.539.jar" "/Users/howard/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.13/httpclient-cache-4.5.13.jar" "/Users/howard/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2-no_aop.jar" "/Users/howard/.m2/repository/clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-resolver-provider/3.8.4/maven-resolver-provider-3.8.4.jar" "/Users/howard/.m2/repository/com/bhauman/spell-spec/0.1.2/spell-spec-0.1.2.jar" "/Users/howard/.m2/repository/com/google/protobuf/protobuf-java/3.19.6/protobuf-java-3.19.6.jar" "/Users/howard/.m2/repository/metosin/reitit-swagger/0.5.18/reitit-swagger-0.5.18.jar" "/Users/howard/.m2/repository/dev/weavejester/ragtime/0.9.3/ragtime-0.9.3.jar" "/Users/howard/.m2/repository/org/apache/maven/resolver/maven-resolver-connector-basic/1.6.3/maven-resolver-connector-basic-1.6.3.jar" "/Users/howard/.m2/repository/metosin/reitit-middleware/0.5.18/reitit-middleware-0.5.18.jar" "/Users/howard/.m2/repository/medley/medley/1.4.0/medley-1.4.0.jar" "/Users/howard/.m2/repository/ring/ring-devel/1.10.0/ring-devel-1.10.0.jar" "/Users/howard/.m2/repository/weavejester/dependency/0.2.1/dependency-0.2.1.jar" "/Users/howard/.m2/repository/rewrite-clj/rewrite-clj/1.1.47/rewrite-clj-1.1.47.jar" "/Users/howard/.m2/repository/compojure/compojure/1.7.0/compojure-1.7.0.jar" "/Users/howard/.m2/repository/metosin/ring-swagger-ui/4.3.0/ring-swagger-ui-4.3.0.jar" "/Users/howard/.m2/repository/buddy/buddy-hashers/2.0.167/buddy-hashers-2.0.167.jar" "/Users/howard/.m2/repository/com/bhauman/cljs-test-display/0.1.1/cljs-test-display-0.1.1.jar" "/Users/howard/.m2/repository/metosin/reitit-malli/0.5.18/reitit-malli-0.5.18.jar" "/Users/howard/.m2/repository/org/jboss/xnio/xnio-api/3.8.0.Final/xnio-api-3.8.0.Final.jar" "/Users/howard/.m2/repository/dev/weavejester/ragtime.core/0.9.3/ragtime.core-0.9.3.jar" "/Users/howard/.m2/repository/com/google/re2j/re2j/1.3/re2j-1.3.jar" "/Users/howard/.m2/repository/thheller/shadow-cljsjs/0.0.22/shadow-cljsjs-0.0.22.jar" "/Users/howard/.m2/repository/org/clojure/spec.alpha/0.3.218/spec.alpha-0.3.218.jar" "/Users/howard/.m2/repository/clj-http/clj-http/3.12.3/clj-http-3.12.3.jar" "/Users/howard/.m2/repository/org/jspecify/jspecify/0.2.0/jspecify-0.2.0.jar" "/Users/howard/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar" "/Users/howard/.m2/repository/com/taoensso/sente/1.19.2/sente-1.19.2.jar" "/Users/howard/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar" "/Users/howard/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.75/bcprov-jdk18on-1.75.jar" "/Users/howard/.m2/repository/potemkin/potemkin/0.4.6/potemkin-0.4.6.jar" "/Users/howard/.m2/repository/babashka/process/0.0.2/process-0.0.2.jar" "/Users/howard/.m2/repository/org/jboss/threads/jboss-threads/3.1.0.Final/jboss-threads-3.1.0.Final.jar" "/Users/howard/.m2/repository/org/clojure/tools.analyzer.jvm/1.2.2/tools.analyzer.jvm-1.2.2.jar" "/Users/howard/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar" "/Users/howard/.gitlibs/libs/org.clojure/tools.deps.alpha/8f8fc2571e721301b6d52e191129248355cb8c5a/src/main/clojure" "/Users/howard/.m2/repository/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar" "/Users/howard/.m2/repository/ring/ring-ssl/0.3.0/ring-ssl-0.3.0.jar" "/Users/howard/.m2/repository/org/clojure/google-closure-library-third-party/0.0-20211011-0726fdeb/google-closure-library-third-party-0.0-20211011-0726fdeb.jar" "/Users/howard/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar" "/Users/howard/.m2/repository/org/java-websocket/Java-WebSocket/1.5.3/Java-WebSocket-1.5.3.jar" "/Users/howard/.m2/repository/borkdude/dynaload/0.2.2/dynaload-0.2.2.jar" "/Users/howard/.m2/repository/com/cognitect/transit-java/1.0.362/transit-java-1.0.362.jar" "/Users/howard/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar" "/Users/howard/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar" "/Users/howard/.m2/repository/binaryage/devtools/1.0.6/devtools-1.0.6.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-builder-support/3.8.4/maven-builder-support-3.8.4.jar" "/Users/howard/.m2/repository/org/clojure/java.classpath/0.3.0/java.classpath-0.3.0.jar" "/Users/howard/.m2/repository/ns-tracker/ns-tracker/0.4.0/ns-tracker-0.4.0.jar" "/Users/howard/.m2/repository/thheller/shadow-cljs/2.20.20/shadow-cljs-2.20.20.jar" "/Users/howard/.m2/repository/org/jboss/logging/jboss-logging/3.4.1.Final/jboss-logging-3.4.1.Final.jar" "/Users/howard/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar" "/Users/howard/.m2/repository/metosin/reitit-dev/0.5.18/reitit-dev-0.5.18.jar" "/Users/howard/.m2/repository/borkdude/edamame/1.1.17/edamame-1.1.17.jar" "/Users/howard/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.0/jackson-datatype-jsr310-2.13.0.jar" "/Users/howard/.m2/repository/ring/ring-jetty-adapter/1.8.2/ring-jetty-adapter-1.8.2.jar" "/Users/howard/.m2/repository/instaparse/instaparse/1.4.8/instaparse-1.4.8.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-core/3.8.4/maven-core-3.8.4.jar" "/Users/howard/.m2/repository/org/clojure/tools.analyzer/1.1.0/tools.analyzer-1.1.0.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-artifact/3.8.4/maven-artifact-3.8.4.jar" "/Users/howard/.m2/repository/prismatic/schema/1.1.12/schema-1.1.12.jar" "/Users/howard/.m2/repository/com/zaxxer/HikariCP/3.3.1/HikariCP-3.3.1.jar" "/Users/howard/.m2/repository/org/clojure/data.priority-map/1.1.0/data.priority-map-1.1.0.jar" "/Users/howard/.m2/repository/org/clojure/core.async/1.6.673/core.async-1.6.673.jar" "/Users/howard/.m2/repository/com/cognitect/transit-clj/1.0.329/transit-clj-1.0.329.jar" "/Users/howard/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar" "/Users/howard/.gitlibs/libs/org.clojure/tools.deps.alpha/8f8fc2571e721301b6d52e191129248355cb8c5a/src/main/resources" "/Users/howard/.m2/repository/thheller/shadow-client/1.3.3/shadow-client-1.3.3.jar" "/Users/howard/.m2/repository/io/undertow/undertow-core/2.2.4.Final/undertow-core-2.2.4.Final.jar" "/Users/howard/.m2/repository/joda-time/joda-time/2.10/joda-time-2.10.jar" "/Users/howard/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar" "/Users/howard/.m2/repository/re-frame/re-frame/1.3.0/re-frame-1.3.0.jar" "/Users/howard/.m2/repository/re-pressed/re-pressed/0.3.2/re-pressed-0.3.2.jar" "/Users/howard/.m2/repository/com/cognitect/transit-js/0.8.874/transit-js-0.8.874.jar" "/Users/howard/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-http/1.6.3/maven-resolver-transport-http-1.6.3.jar" "/Users/howard/.m2/repository/io/aviso/pretty/1.1.1/pretty-1.1.1.jar" "/Users/howard/.m2/repository/day8/re-frame/tracing/0.6.2/tracing-0.6.2.jar" "/Users/howard/.m2/repository/org/eclipse/jetty/jetty-client/9.4.44.v20210927/jetty-client-9.4.44.v20210927.jar" "/Users/howard/.m2/repository/metosin/reitit-frontend/0.5.18/reitit-frontend-0.5.18.jar" "/Users/howard/.m2/repository/ring/ring-servlet/1.8.2/ring-servlet-1.8.2.jar" "/Users/howard/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.jar" "/Users/howard/.m2/repository/org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar" "/Users/howard/.m2/repository/org/clojure/tools.reader/1.3.6/tools.reader-1.3.6.jar" "/Users/howard/.m2/repository/org/clojure/clojure/1.11.1/clojure-1.11.1.jar" "/Users/howard/.m2/repository/com/google/auto/value/auto-value-annotations/1.6/auto-value-annotations-1.6.jar" "/Users/howard/.m2/repository/ring/ring-anti-forgery/1.3.0/ring-anti-forgery-1.3.0.jar" "/Users/howard/.m2/repository/metosin/reitit-http/0.5.18/reitit-http-0.5.18.jar" "/Users/howard/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar" "/Users/howard/.m2/repository/com/google/code/gson/gson/2.9.1/gson-2.9.1.jar" "/Users/howard/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-repository-metadata/3.8.4/maven-repository-metadata-3.8.4.jar" "/Users/howard/.m2/repository/clojure-future-spec/clojure-future-spec/1.9.0/clojure-future-spec-1.9.0.jar" "/Users/howard/.m2/repository/metosin/reitit-sieppari/0.5.18/reitit-sieppari-0.5.18.jar" "/Users/howard/.m2/repository/mvxcvi/puget/1.1.2/puget-1.1.2.jar" "/Users/howard/.m2/repository/reagent/reagent/1.2.0/reagent-1.2.0.jar" "/Users/howard/.m2/repository/metosin/malli/0.8.2/malli-0.8.2.jar" "/Users/howard/.m2/repository/org/apache/maven/resolver/maven-resolver-impl/1.6.3/maven-resolver-impl-1.6.3.jar" "/Users/howard/.m2/repository/ring/ring-headers/0.3.0/ring-headers-0.3.0.jar" "/Users/howard/.m2/repository/nrepl/nrepl/1.0.0/nrepl-1.0.0.jar" "/Users/howard/.m2/repository/com/taoensso/truss/1.10.1/truss-1.10.1.jar" "/Users/howard/.m2/repository/metosin/reitit-swagger-ui/0.5.18/reitit-swagger-ui-0.5.18.jar" "/Users/howard/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.13.3/jackson-dataformat-cbor-2.13.3.jar" "/Users/howard/.m2/repository/com/google/errorprone/error_prone_annotations/2.15.0/error_prone_annotations-2.15.0.jar" "/Users/howard/.m2/repository/meta-merge/meta-merge/1.0.0/meta-merge-1.0.0.jar" "/Users/howard/.m2/repository/metosin/jsonista/0.3.5/jsonista-0.3.5.jar" "/Users/howard/.m2/repository/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar" "/Users/howard/.m2/repository/org/clojure/clojurescript/1.11.60/clojurescript-1.11.60.jar" "/Users/howard/.m2/repository/lambdaisland/deep-diff/0.0-47/deep-diff-0.0-47.jar" "/Users/howard/.m2/repository/org/clojure/java.data/1.0.95/java.data-1.0.95.jar" "/Users/howard/.m2/repository/day8/re-frame/re-frame-10x/1.8.1/re-frame-10x-1.8.1.jar" "/Users/howard/.m2/repository/crypto-equality/crypto-equality/1.0.0/crypto-equality-1.0.0.jar" "/Users/howard/.m2/repository/metosin/spec-tools/0.10.5/spec-tools-0.10.5.jar" "/Users/howard/.m2/repository/com/taoensso/encore/3.62.1/encore-3.62.1.jar" "/Users/howard/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.3/jackson-core-2.13.3.jar" "/Users/howard/.m2/repository/org/wildfly/client/wildfly-client-config/1.0.1.Final/wildfly-client-config-1.0.1.Final.jar" "/Users/howard/.m2/repository/org/babashka/sci.impl.types/0.0.2/sci.impl.types-0.0.2.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-model-builder/3.8.4/maven-model-builder-3.8.4.jar" "/Users/howard/.m2/repository/org/eclipse/jetty/jetty-util/9.4.44.v20210927/jetty-util-9.4.44.v20210927.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-plugin-api/3.8.4/maven-plugin-api-3.8.4.jar" "/Users/howard/.m2/repository/clj-time/clj-time/0.15.2/clj-time-0.15.2.jar" "/Users/howard/.m2/repository/org/eclipse/jetty/jetty-server/9.4.31.v20200723/jetty-server-9.4.31.v20200723.jar" "/Users/howard/.m2/repository/org/clojure/core.cache/1.0.225/core.cache-1.0.225.jar" "/Users/howard/.m2/repository/org/apache/maven/maven-settings/3.8.4/maven-settings-3.8.4.jar" "/Users/howard/.m2/repository/org/clojure/tools.gitlibs/2.4.181/tools.gitlibs-2.4.181.jar" "/Users/howard/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar" "/Users/howard/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar" "/Users/howard/.m2/repository/thheller/shadow-util/0.7.0/shadow-util-0.7.0.jar" "/Users/howard/.m2/repository/org/clojure/data.json/2.4.0/data.json-2.4.0.jar" "/Users/howard/.m2/repository/org/clojure/core.rrb-vector/0.1.2/core.rrb-vector-0.1.2.jar"] java.lang.reflect.InvocationTargetException
Running tests for the development project using test runner: Polylith built-in clojure.test runner...
Running tests from the development project, including 10 bricks: auth, channels, database, messages, socket, subscriptions, teams, tools, users, api-server
clojure.lang.ExceptionInfo: Error while evaluating form (do (clojure.core/use (quote clojure.test)) (clojure.core/require (quote com.howard.uchat.backend.api-server.core-test)) (clojure.test/run-tests (quote com.howard.uchat.backend.api-server.core-test))) in class-loader. Cause: java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because "class_loader" is null {:form (do (clojure.core/use (quote clojure.test)) (clojure.core/require (quote com.howard.uchat.backend.api-server.core-test)) (clojure.test/run-tests (quote com.howard.uchat.backend.api-server.core-test)))}
        at polylith.clj.core.test_runner_orchestrator.core$__GT_eval_in_project$fn__7829.invoke(core.clj:107)
        at polylith.clj.core.clojure_test_test_runner.core$run_test_statements$fn__173.invoke(core.clj:59)
        at polylith.clj.core.clojure_test_test_runner.core$run_test_statements.invokeStatic(core.clj:58)
        at polylith.clj.core.clojure_test_test_runner.core$run_test_statements.invoke(core.clj:52)
        at polylith.clj.core.clojure_test_test_runner.core$create$reify__200.run_tests(core.clj:98)
        at polylith.clj.core.test_runner_orchestrator.core$run_tests_for_project_with_test_runner.invokeStatic(core.clj:88)
        at polylith.clj.core.test_runner_orchestrator.core$run_tests_for_project.invokeStatic(core.clj:146)
        at polylith.clj.core.test_runner_orchestrator.core$run.invokeStatic(core.clj:212)
        at polylith.clj.core.test_runner_orchestrator.interface$run.invokeStatic(interface.clj:4)
        at polylith.clj.core.command.test$run.invokeStatic(test.clj:9)
        at polylith.clj.core.command.core$execute.invokeStatic(core.clj:76)
        at polylith.clj.core.command.interface$execute_command.invokeStatic(interface.clj:4)
        at polylith.clj.core.poly_cli.core$_main.invokeStatic(core.clj:31)
        at polylith.clj.core.poly_cli.core$_main.doInvoke(core.clj:7)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at polylith.clj.core.poly_cli.core.main(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because "class_loader" is null
        at polylith.clj.core.common.class_loader$invoke_in_STAR_.invokeStatic(class_loader.clj:28)
        at polylith.clj.core.common.class_loader$eval_in_STAR_$print_read_eval__235.invoke(class_loader.clj:46)
        at polylith.clj.core.common.class_loader$eval_in_STAR_.invokeStatic(class_loader.clj:51)
        at polylith.clj.core.common.class_loader$eval_in.invokeStatic(class_loader.clj:60)
        at polylith.clj.core.common.interface$eval_in.invokeStatic(interface.clj:22)
        ... 16 more
Couldn't run test statement for the development project: (do (clojure.core/use (quote clojure.test)) (clojure.core/require (quote com.howard.uchat.backend.api-server.core-test)) (clojure.test/run-tests (quote com.howard.uchat.backend.api-server.core-test))) clojure.lang.ExceptionInfo: Error while evaluating form (do (clojure.core/use (quote clojure.test)) (clojure.core/require (quote com.howard.uchat.backend.api-server.core-test)) (clojure.test/run-tests (quote com.howard.uchat.backend.api-server.core-test))) in class-loader. Cause: java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because "class_loader" is null {:form (do (clojure.core/use (quote clojure.test)) (clojure.core/require (quote com.howard.uchat.backend.api-server.core-test)) (clojure.test/run-tests (quote com.howard.uchat.backend.api-server.core-test)))}
```
seems that can't create class loader.

**To Reproduce**
Java version: openjdk version "20.0.1" 2023-04-18
poly version:   0.2.17-alpha (2022-12-09)
clojure version: Clojure CLI version 1.11.1.1347
OS: Mac Morterey: 12.6.7

project path: 
https://github.com/idhowardgj94/uchat-mono
branch:  chore/prductionize

**Expected behavior**
Run all test under development

**Screenshots**
<img width="1423" alt="圖片" src="https://github.com/polyfy/polylith/assets/11270695/ef3a21fd-8e45-45ea-b1b1-91cbd92d2c40">

**Workspace Attachment**
If applicable, add output of following command as attachment:
Noting show

**Operating System (please complete the following information):**
 - OS: Mac Morterey
 - Version: 12.6.7

**Versions (please complete the following information):**
- Java version: openjdk version "20.0.1" 2023-04-18
- poly version:   0.2.17-alpha (2022-12-09)
- clojure version: Clojure CLI version 1.11.1.1347

**Additional context**
N/A

**Comment by idhowardgj94** [comment]
hmmm it's because there is a small bug in my codebase.
sorry lol
